

services:
  zookeeper:
    image: zookeeper:latest
    platform: linux/amd64
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      # Optional environment variables for Zookeeper
      ZOO_HEAP_SIZE: "512m"  # Uncomment and set memory limits if needed

    networks:
      - kafka-net
    volumes:
      - zookeeper-data:/data
      - zookeeper-log:/datalog
    pull_policy: missing

  kafka:
    image: confluentinc/cp-kafka:latest
    platform: linux/amd64
    container_name: kafka
    ports:
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"  # Zookeeper connection

      # Advertised listeners
      KAFKA_ADVERTISED_LISTENERS: "INSIDE://kafka:9092,OUTSIDE://localhost:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
      KAFKA_LISTENERS: "INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093"

      # Inter-broker communication listener
      KAFKA_INTER_BROKER_LISTENER_NAME: "INSIDE"

      # Handling large message sizes
      KAFKA_MAX_REQUEST_SIZE: "209715200"
      KAFKA_MESSAGE_MAX_BYTES: "209715200"

      # Offset topic replication
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"

    depends_on:
      - zookeeper
    networks:
      - kafka-net
    volumes:
      - kafka-data:/var/lib/kafka/data
    pull_policy: missing

networks:
  kafka-net:
    driver: bridge

volumes:
  zookeeper-data:
    driver: local
  zookeeper-log:
    driver: local
  kafka-data:
    driver: local
