# Use the official Python image as the base
FROM python:3.10-slim

# Install system dependencies (including GDAL and dependencies for PostGIS and Django)
RUN apt-get update && \
    apt-get install -y \
    gdal-bin \
    libgdal-dev \
    build-essential \
    libpq-dev \
    bash \
    && rm -rf /var/lib/apt/lists/*

# Set environment variables for Python and GDAL
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory
WORKDIR /app

# Copy the requirements.txt to the container
COPY requirements.txt /app/

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the project files
COPY . /app/

# Copy the wait-for-it.sh script into the container and make it executable
COPY wait-for-it.sh /app/wait-for-it.sh
RUN chmod +x /app/wait-for-it.sh

# Run collectstatic to gather static files for Django
RUN python manage.py collectstatic --noinput

# Expose port 8000 for ASGI server
EXPOSE 8000

# Use wait-for-it.sh to wait for the Kafka service (or any other services)
# Then run Django ASGI server using Daphne
CMD ["./wait-for-it.sh", "kafka:9092", "--", "daphne", "-b", "0.0.0.0", "-p", "8000", "TRIV.asgi:application"]
